export type AgeGroup = "1-2" | "2-3" | "4-5" | "6-7" | "8-10"

/** Packs classiques (hors livrets tout-petits 1–2) */
export type PackAgeGroup = Exclude<AgeGroup, "1-2">

/**
 * Thèmes catalogue (filtres bibliothèque).
 * Règles : un thème « découverte » principal par pack (+ `lecture` si activités lecture/écriture).
 * - animaux : espèce dédiée (papillon, serpent, coccinelle, abeilles) — pas les packs géo.
 * - continents : géographie (continents, océan, Afrique, Antarctique) — pas `animaux`.
 * - asie : découverte régionale Asie.
 * - saisons : pack méta « Les saisons » uniquement — pas fêtes ni géo.
 * - botanique : plantes (tournesols, cerise).
 * - histoire / animes : comme leur nom.
 * Fêtes (Halloween, Noël) : filtre saison seulement (automne / hiver), pas de thème catalogue.
 */
export type Theme =
  | "saisons"
  | "animaux"
  | "botanique"
  | "continents"
  | "histoire"
  | "lecture"
  | "animes"
  | "asie"

export type Season = "printemps" | "ete" | "automne" | "hiver" | "toute-annee"

/** Catalogue public = packs uniquement (5–8 activités hors couverture). */
export type ActivityType = "pack"

export type Activity = {
  slug: string
  title: string
  subtitle: string
  description: string
  type: ActivityType
  ages: AgeGroup[]
  themes: Theme[]
  season: Season
  color: "berry" | "sun" | "sky" | "leaf" | "tangerine"
  emojiFree: boolean // gratuit
  /** Pages imprimées ≈ 1 couverture + activityCount (5–8) */
  pageCount: number
}

export const AGE_LABELS: Record<AgeGroup, string> = {
  "1-2": "1-2 ans",
  "2-3": "2-3 ans",
  "4-5": "4-5 ans",
  "6-7": "6-7 ans",
  "8-10": "8-10 ans",
}

export const THEME_LABELS: Record<Theme, string> = {
  saisons: "Saisons",
  animaux: "Animaux",
  botanique: "Botanique",
  continents: "Continents",
  histoire: "Histoire",
  lecture: "Lecture & écriture",
  animes: "Animés",
  asie: "Asie",
}

export const SEASON_LABELS: Record<Season, string> = {
  printemps: "Printemps",
  ete: "Été",
  automne: "Automne",
  hiver: "Hiver",
  "toute-annee": "Toute l'année",
}

/**
 * Bibliothèque publique — **packs seulement**.
 * Fiches composantes (anatomie, drapeaux, syllabes…) vivent dans les packs, pas en solo.
 */
export const activities: Activity[] = [
  {
    slug: "pack-tournesols-2-3",
    title: "Les tournesols",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Coloriage tournesol, abeille, cartes à nommer à voix haute, tracé et symétrie simple. Gros gestes, à vivre avec un adulte.",
    type: "pack",
    ages: ["2-3"],
    themes: ["botanique"],
    season: "ete",
    color: "sun",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-tournesols",
    title: "Les tournesols",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Anatomie 5 parties, cartes, syllabes, abeille, symétrie, écriture, et cycle de vie en rond avec étiquettes à coller.",
    type: "pack",
    ages: ["4-5"],
    themes: ["botanique", "lecture"],
    season: "ete",
    color: "sun",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-tournesols-6-7",
    title: "Les tournesols",
    subtitle: "Pack lecture & observation — 6-7 ans",
    description:
      "Version défi : anatomie à 6 parties, nomenclature séparée, syllabes à 2 trous, chemin zigzag, 5 mots à écrire, et le cycle de vie du tournesol.",
    type: "pack",
    ages: ["6-7"],
    themes: ["botanique", "lecture"],
    season: "ete",
    color: "sun",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-tournesols-8-10",
    title: "Les tournesols",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Anatomie précise, nomenclature, mots croisés, mots fléchés + vrai/faux, symétrie, phrases, cycle de vie à raconter.",
    type: "pack",
    ages: ["8-10"],
    themes: ["botanique", "lecture"],
    season: "ete",
    color: "sun",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-saisons-2-3",
    title: "Les saisons",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Roue des saisons, coloriages, cartes photos à nommer, tracé et associations. Gros gestes avec un adulte.",
    type: "pack",
    ages: ["2-3"],
    themes: ["saisons"],
    season: "toute-annee",
    color: "sun",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-saisons",
    title: "Les saisons",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Roue améliorée, nomenclature photos, cycle en rond + étiquettes, coloriage, écriture, associations et « Le savais-tu ? ».",
    type: "pack",
    ages: ["4-5"],
    themes: ["saisons"],
    season: "toute-annee",
    color: "sun",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-saisons-6-7",
    title: "Les saisons",
    subtitle: "Pack lecture & observation — 6-7 ans",
    description:
      "Roue à compléter, nomenclature séparée, syllabes, chemin, écriture, ordre de l'année et faits doux.",
    type: "pack",
    ages: ["6-7"],
    themes: ["saisons", "lecture"],
    season: "toute-annee",
    color: "sun",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-saisons-8-10",
    title: "Les saisons",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Cycle + observations, nomenclature, mots croisés, phrases, ordre à raconter, vrai/faux et « Le savais-tu ? ».",
    type: "pack",
    ages: ["8-10"],
    themes: ["saisons", "lecture"],
    season: "toute-annee",
    color: "sun",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-continents",
    title: "Continents & drapeaux",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Boussole, drapeaux du monde à colorier, chemin, écriture de pays et continents.",
    type: "pack",
    ages: ["4-5"],
    themes: ["continents"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-continents-6-7",
    title: "Continents & drapeaux",
    subtitle: "Pack lecture & géographie — 6-7 ans",
    description:
      "Drapeaux, syllabes de pays, chemin, écriture, voyage à ordonner et continents.",
    type: "pack",
    ages: ["6-7"],
    themes: ["continents", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-continents-8-10",
    title: "Continents & drapeaux",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Drapeaux, syllabes, phrases, voyage, classification continents et vrai/faux.",
    type: "pack",
    ages: ["8-10"],
    themes: ["continents", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-moyen-age",
    title: "Le Moyen Âge",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Coloriage du château, nomenclature (chevalier, dragon, couronne…), chemin du chevalier, écriture, et blason à colorier.",
    type: "pack",
    ages: ["4-5"],
    themes: ["histoire"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-moyen-age-6-7",
    title: "Le Moyen Âge",
    subtitle: "Pack lecture & histoire — 6-7 ans",
    description:
      "Nomenclature, chemin zigzag, syllabes, écriture, blason en miroir, et journée médiévale à remettre en ordre.",
    type: "pack",
    ages: ["6-7"],
    themes: ["histoire", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-moyen-age-8-10",
    title: "Le Moyen Âge",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, chemin défi, syllabes, phrases, blason + nom de maison, frise et vrai/faux.",
    type: "pack",
    ages: ["8-10"],
    themes: ["histoire", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-one-piece",
    title: "L'univers de One Piece",
    subtitle: "Pack découverte — 6-7 ans",
    description:
      "Bateau pirate, nomenclature, chemin vers le trésor, syllabes, aventure à ordonner et vrai/faux.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "tangerine",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-one-piece-8-10",
    title: "L'univers de One Piece",
    subtitle: "Pack découverte — 8-10 ans",
    description:
      "Nomenclature, mots croisés, lecture, fléchés, phrases, comparaison, récit et vrai/faux.",
    type: "pack",
    ages: ["8-10"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "tangerine",
    emojiFree: true,
    pageCount: 9,
  },
  {
    slug: "pack-pat-patrouille",
    title: "L'univers de Pat' Patrouille",
    subtitle: "Pack secours — 4-5 ans",
    description:
      "Coloriage du chiot, nomenclature, chemin vers la tour, écriture, et associer missions.",
    type: "pack",
    ages: ["4-5"],
    themes: ["animes"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-pat-patrouille-6-7",
    title: "L'univers de Pat' Patrouille",
    subtitle: "Pack lecture & missions — 6-7 ans",
    description:
      "Nomenclature, chemin zigzag, syllabes, écriture, mission à ordonner et vrai/faux.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-pat-patrouille-8-10",
    title: "L'univers de Pat' Patrouille",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature + écrire, chemin défi, syllabes, phrases, mission à raconter et vrai/faux.",
    type: "pack",
    ages: ["8-10"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-pyjamasques",
    title: "L'univers des Pyjamasques",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Coloriage du héros chat, nomenclature, chemin vers le QG, écriture, et soirée de héros à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: ["animes"],
    season: "toute-annee",
    color: "berry",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-pyjamasques-6-7",
    title: "L'univers des Pyjamasques",
    subtitle: "Pack découverte — 6-7 ans",
    description:
      "Nomenclature, chemin zigzag, syllabes, écriture, mission nocturne à ordonner et vrai/faux.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-pyjamasques-8-10",
    title: "L'univers des Pyjamasques",
    subtitle: "Pack découverte — 8-10 ans",
    description:
      "Nomenclature + écrire, chemin défi, syllabes, phrases, mission à raconter et vrai/faux.",
    type: "pack",
    ages: ["8-10"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-gabby-chat",
    title: "L'univers de Gabby et la maison magique des chats",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Coloriage de la maison, nomenclature, chemin du chaton, écriture, et associer amis & objets.",
    type: "pack",
    ages: ["4-5"],
    themes: ["animes"],
    season: "toute-annee",
    color: "berry",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-gabby-chat-6-7",
    title: "L'univers de Gabby et la maison magique des chats",
    subtitle: "Pack découverte — 6-7 ans",
    description:
      "Nomenclature, chemin zigzag, syllabes, écriture, visite à ordonner et vrai/faux.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-gabby-chat-8-10",
    title: "L'univers de Gabby et la maison magique des chats",
    subtitle: "Pack découverte — 8-10 ans",
    description:
      "Nomenclature + écrire, chemin défi, phrases, associer amis & objets, visite à raconter et vrai/faux.",
    type: "pack",
    ages: ["8-10"],
    themes: ["animes", "lecture"],
    season: "toute-annee",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-asie-2-3",
    title: "Découvrir l'Asie",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Panda, bambou, fleur : coloriage, vocabulaire oral, tracé et associations simples. À vivre avec un adulte.",
    type: "pack",
    ages: ["2-3"],
    themes: ["asie"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-asie",
    title: "Découvrir l'Asie",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Montagne, nomenclature (panda, riz, lanterne…), chemin, écriture et petit voyage à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: ["asie", "continents"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-asie-6-7",
    title: "Découvrir l'Asie",
    subtitle: "Pack lecture & géographie — 6-7 ans",
    description:
      "Nomenclature, chemin, syllabes (Japon, Inde…), écriture, drapeaux d'Asie et voyage à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["asie", "continents", "lecture"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-asie-8-10",
    title: "Découvrir l'Asie",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, chemin défi, syllabes, phrases, pays & symboles, vrai/faux sur le continent.",
    type: "pack",
    ages: ["8-10"],
    themes: ["asie", "continents", "lecture"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-papillon-2-3",
    title: "Le papillon",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Coloriage papillon et chenille, cartes à nommer, tracé et associations simples. À vivre avec un adulte.",
    type: "pack",
    ages: ["2-3"],
    themes: ["animaux"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-papillon",
    title: "Le papillon",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Coloriage, anatomie simple, nomenclature (12 photos), syllabes, écriture, cycle de vie en rond et associations.",
    type: "pack",
    ages: ["4-5"],
    themes: ["animaux", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-papillon-6-7",
    title: "Le papillon",
    subtitle: "Pack lecture & nature — 6-7 ans",
    description:
      "Nomenclature, syllabes, chemin zigzag, écriture et cycle chenille → chrysalide → papillon à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animaux", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-papillon-8-10",
    title: "Le papillon",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature + écrire, mots croisés, phrases, cycle à raconter et vrai/faux sciences douces.",
    type: "pack",
    ages: ["8-10"],
    themes: ["animaux", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-serpent-2-3",
    title: "Le serpent",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Coloriage serpent et œuf, cartes à nommer, tracé et associations simples. Curiosité douce avec un adulte.",
    type: "pack",
    ages: ["2-3"],
    themes: ["animaux"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-serpent",
    title: "Le serpent",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Coloriage contour, anatomie 5 parties, nomenclature (12 photos), syllabes, écriture, cycle de vie en rond et habitats.",
    type: "pack",
    ages: ["4-5"],
    themes: ["animaux", "lecture"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 8,
  },
  {
    slug: "pack-serpent-6-7",
    title: "Le serpent",
    subtitle: "Pack lecture & nature — 6-7 ans",
    description:
      "Nomenclature, syllabes, chemin zigzag, écriture et habitats / ordre de vie à associer.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animaux", "lecture"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-serpent-8-10",
    title: "Le serpent",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature + écrire, mots croisés, phrases, habitats et vrai/faux curiosité douce.",
    type: "pack",
    ages: ["8-10"],
    themes: ["animaux", "lecture"],
    season: "toute-annee",
    color: "leaf",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-coccinelle-2-3",
    title: "La coccinelle",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Coloriage coccinelle et feuille, cartes à nommer, tracé et associations simples. À vivre avec un adulte.",
    type: "pack",
    ages: ["2-3"],
    themes: ["animaux"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-coccinelle",
    title: "La coccinelle",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Anatomie 5 parties, nomenclature jardin, syllabes, chemin, écriture et cycle œuf → larve → nymphe → adulte.",
    type: "pack",
    ages: ["4-5"],
    themes: ["animaux", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-coccinelle-6-7",
    title: "La coccinelle",
    subtitle: "Pack lecture & nature — 6-7 ans",
    description:
      "Anatomie détaillée, nomenclature, défi syllabes, chemin zigzag, écriture et cycle à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animaux", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-coccinelle-8-10",
    title: "La coccinelle",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Anatomie (élytres, pronotum…), mots croisés, phrases, cycle à raconter et vrai/faux sciences douces.",
    type: "pack",
    ages: ["8-10"],
    themes: ["animaux", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-antarctique-2-3",
    title: "L'Antarctique",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Pingouin, phoque, flocon : coloriages, vocabulaire oral, tracé et associations simples. À vivre avec un adulte.",
    type: "pack",
    ages: ["2-3"],
    themes: ["continents"],
    season: "hiver",
    color: "sky",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-antarctique",
    title: "L'Antarctique",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Pingouin, phoque, igloo : coloriage, nomenclature, chemin, écriture, associations et journée polaire à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: ["continents", "lecture"],
    season: "hiver",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-antarctique-6-7",
    title: "L'Antarctique",
    subtitle: "Pack lecture & froid — 6-7 ans",
    description:
      "Nomenclature, chemin zigzag, syllabes du froid, écriture et journée polaire à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["continents", "lecture"],
    season: "hiver",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-antarctique-8-10",
    title: "L'Antarctique",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, syllabes avancées, phrases, banquise à classer, vrai/faux et expédition à raconter.",
    type: "pack",
    ages: ["8-10"],
    themes: ["continents", "lecture"],
    season: "hiver",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-ocean-2-3",
    title: "L'océan",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Poisson, baleine, vague : coloriages, vocabulaire oral, tracé et associations simples.",
    type: "pack",
    ages: ["2-3"],
    themes: ["continents"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-ocean",
    title: "L'océan",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Poisson, baleine, coquillage : coloriage, nomenclature, chemin, écriture, associations et sortie mer à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: ["continents"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-ocean-6-7",
    title: "L'océan",
    subtitle: "Pack lecture & observation — 6-7 ans",
    description:
      "Nomenclature, chemin vers le bateau, syllabes de la mer, écriture, associations et plongée à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["continents", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-ocean-8-10",
    title: "L'océan",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, phrases, zones de l'océan, vrai/faux, expédition à raconter et chemin défi pieuvre.",
    type: "pack",
    ages: ["8-10"],
    themes: ["continents", "lecture"],
    season: "toute-annee",
    color: "sky",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-cerise-2-3",
    title: "La cerise",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Cerises, fleur, arbre : coloriages, vocabulaire oral, tracé et associations simples.",
    type: "pack",
    ages: ["2-3"],
    themes: ["botanique"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-cerise",
    title: "La cerise",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Fleurs, fruits et panier : coloriage, nomenclature, chemin, écriture, associations et cueillette à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: ["botanique"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-cerise-6-7",
    title: "La cerise",
    subtitle: "Pack lecture & botanique — 6-7 ans",
    description:
      "Nomenclature, chemin vers l'arbre, syllabes, écriture, botanique à associer et cycle à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["botanique", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-cerise-8-10",
    title: "La cerise",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, phrases, botanique à classer, vrai/faux, cycle à raconter et syllabes avancées.",
    type: "pack",
    ages: ["8-10"],
    themes: ["botanique", "lecture"],
    season: "printemps",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-afrique",
    title: "L'Afrique",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Lion, girafe, acacia : coloriage, nomenclature, chemin, écriture, associations et journée savane à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: ["continents"],
    season: "toute-annee",
    color: "sun",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-afrique-6-7",
    title: "L'Afrique",
    subtitle: "Pack lecture & savane — 6-7 ans",
    description:
      "Lion, éléphant, baobab : coloriage, nomenclature, chemin, syllabes, associations et vrai/faux sur la savane.",
    type: "pack",
    ages: ["6-7"],
    themes: ["continents", "lecture"],
    season: "toute-annee",
    color: "sun",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-afrique-8-10",
    title: "L'Afrique",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, syllabes avancées, phrases, savane à classer, vrai/faux et migration à raconter.",
    type: "pack",
    ages: ["8-10"],
    themes: ["continents", "lecture"],
    season: "toute-annee",
    color: "sun",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-halloween-2-3",
    title: "Halloween",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Citrouille, fantôme : coloriages, vocabulaire oral, tracé et associations douces.",
    type: "pack",
    ages: ["2-3"],
    themes: [],
    season: "automne",
    color: "tangerine",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-halloween",
    title: "Halloween",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Citrouille amicale, lune et bonbons : coloriage, nomenclature, chemin, écriture, associations et soirée à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: [],
    season: "automne",
    color: "tangerine",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-halloween-6-7",
    title: "Halloween",
    subtitle: "Pack lecture & automne — 6-7 ans",
    description:
      "Nomenclature, chemin vers la lune, syllabes d'automne, écriture, symboles et soirée à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["lecture"],
    season: "automne",
    color: "tangerine",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-halloween-8-10",
    title: "Halloween",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, phrases, automne à classer, vrai/faux, soirée à raconter et chemin défi chauve-souris.",
    type: "pack",
    ages: ["8-10"],
    themes: ["lecture"],
    season: "automne",
    color: "tangerine",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-noel-2-3",
    title: "Noël",
    subtitle: "Pack sensoriel — 2-3 ans",
    description:
      "Sapin, étoile, cadeau : coloriages, vocabulaire oral, tracé et associations simples.",
    type: "pack",
    ages: ["2-3"],
    themes: [],
    season: "hiver",
    color: "berry",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-noel",
    title: "Noël",
    subtitle: "Pack découverte — 4-5 ans",
    description:
      "Sapin, étoile et cadeaux : coloriage, nomenclature, chemin, écriture, associations et fête à ordonner.",
    type: "pack",
    ages: ["4-5"],
    themes: ["saisons"],
    season: "hiver",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-noel-6-7",
    title: "Noël",
    subtitle: "Pack lecture & hiver — 6-7 ans",
    description:
      "Nomenclature, chemin vers le sapin, syllabes de l'hiver, écriture, symboles et fête à ordonner.",
    type: "pack",
    ages: ["6-7"],
    themes: ["lecture"],
    season: "hiver",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-noel-8-10",
    title: "Noël",
    subtitle: "Pack autonomie — 8-10 ans",
    description:
      "Nomenclature, phrases, hiver à classer, vrai/faux, matinée à raconter et chemin défi renne.",
    type: "pack",
    ages: ["8-10"],
    themes: ["lecture"],
    season: "hiver",
    color: "berry",
    emojiFree: true,
    pageCount: 7,
  },
  {
    slug: "pack-livret-abeilles-1-2",
    title: "Les abeilles",
    subtitle: "Livret co-schooling — 1-2 ans",
    description:
      "Livret tout-petits : nomenclature orale, coloriage, couleurs, son Bzzz et jeux simples. À vivre avec un adulte.",
    type: "pack",
    ages: ["1-2"],
    themes: ["animaux"],
    season: "printemps",
    color: "sun",
    emojiFree: true,
    pageCount: 6,
  },
  {
    slug: "pack-livret-abeilles-6-7",
    title: "Les abeilles",
    subtitle: "Livret co-schooling — 6-7 ans",
    description:
      "Livret A4 court : 8 pages, 8 activités variées autour des pollinisateurs. À faire avec un adulte.",
    type: "pack",
    ages: ["6-7"],
    themes: ["animaux", "lecture"],
    season: "printemps",
    color: "sun",
    emojiFree: true,
    pageCount: 8,
  },
]

export function getActivity(slug: string) {
  return activities.find((a) => a.slug === slug)
}
